In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
sent=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
]

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
## Define the vocabulary size
voc_size=10000

In [10]:
###One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5979, 5678, 2884, 7993],
 [5979, 5678, 2884, 416],
 [5979, 2891, 2884, 4328],
 [4327, 5151, 3845, 770, 8915],
 [4327, 5151, 3845, 770, 6891],
 [534, 5979, 2670, 2884, 4437],
 [621, 8286, 9202, 770]]

You can see the vectors have been created using OHE and a vocabulary size of 10000. We will now pass the sentences one by one into the embedding layer for word-embedding representation

In [11]:
## word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

**What is PAD_SEQUENCES:** The `pad_sequences` library helps us to ensure each sentences are represented in the same size. If not we cant train.

In [13]:
sent_length=8

In [14]:
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) ## This will pad the sentence with 0's at the start to complete a size of 8
print(embedded_docs)

[[   0    0    0    0 5979 5678 2884 7993]
 [   0    0    0    0 5979 5678 2884  416]
 [   0    0    0    0 5979 2891 2884 4328]
 [   0    0    0 4327 5151 3845  770 8915]
 [   0    0    0 4327 5151 3845  770 6891]
 [   0    0    0  534 5979 2670 2884 4437]
 [   0    0    0    0  621 8286 9202  770]]


In [16]:
## feature representation
dim=10 ## just like in our example in the note, we used 300.

In [21]:
model = Sequential()

model.add(Embedding(voc_size, 10, input_length=sent_length))

model.build(input_shape=(None, sent_length))

model.compile(optimizer='adam', loss='mse')

In [22]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

What we just did is create the embedding layer which will be used to transform the words into vectors. NOTE: This is just a simple process we applied.

In [24]:
## Now lets get them converted
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step


array([[[-0.01405942, -0.0499416 ,  0.04388856, -0.01508275,
         -0.01150061,  0.0436075 , -0.01760935, -0.00555587,
         -0.02002769, -0.01020507],
        [-0.01405942, -0.0499416 ,  0.04388856, -0.01508275,
         -0.01150061,  0.0436075 , -0.01760935, -0.00555587,
         -0.02002769, -0.01020507],
        [-0.01405942, -0.0499416 ,  0.04388856, -0.01508275,
         -0.01150061,  0.0436075 , -0.01760935, -0.00555587,
         -0.02002769, -0.01020507],
        [-0.01405942, -0.0499416 ,  0.04388856, -0.01508275,
         -0.01150061,  0.0436075 , -0.01760935, -0.00555587,
         -0.02002769, -0.01020507],
        [-0.02254339, -0.00239923, -0.02468156, -0.01028106,
          0.00974164,  0.0497527 ,  0.00641686, -0.02999214,
         -0.03273077,  0.03862103],
        [-0.03365079,  0.0456017 , -0.01525792,  0.0426509 ,
         -0.03687491, -0.03115505, -0.0062563 ,  0.04554475,
         -0.02220228, -0.0129657 ],
        [-0.01558051, -0.01552763, -0.02729199,  0.0

You can see every word is represented in 10 dimensions like we initialized.